### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by fede843** [laromicas/docker-romvault#1]
Hello, is there any advance in the ARM support side?

**Comment by fede843** [comment]
OK, I have just cloned the repo, tried to locally build it in a rpi4 64 bits OS.
It built straight away. Just a minor bug when booting up, when executing https://github.com/laromicas/docker-romvault/blob/add19315872b39f11f960b0eba30883d0a7eb1c0/rootfs/etc/cont-init.d/99-romvault#L13 /etc/openbox dir does not exist. Had manually added an extra Dockerfile step to handle that. After that it seems all good.
Testing it under ARM, let's see how it goes.

**Comment by laromicas** [comment]
It will be good to add support for ARM. Great work. I will check the bug you mention and let you know. Thanks.

**Comment by fede843** [comment]
2 quick ones:

![image](https://user-images.githubusercontent.com/7727637/235168239-c12cd21f-1a5b-40f1-9961-51f1764f6a3a.png)

Do you get the same missing field names (inside Dat Info and Game Info panels) in GUI in other platforms or is something related to my local ARM build?

An the final one, not sure how the web and VNC are related, but if they are separate in their domains, can we disable VNC with some env or parameter? The listening port -1 does not prevent for the daemon to run in container.
This is an ignorant person question, web probably needs VNC running, but still I am asking it.

**Comment by fede843** [comment]
Also, I have just updated the docker base image to 3.17 both for alpine and the baseimage-gui. Container seems fine so far.

**Comment by laromicas** [comment]
Just to let you know, any contribution is welcome, feel free to open a pull request anytime.

**Comment by laromicas** [comment]
Added rpi64 bit support for the image as you tell me it runs, I will leave this issue open until I test it myself or you confirm it works.

**Comment by fede843** [comment]
Understood, I will test that later

**Comment by fede843** [comment]
I have built the latest locally and it works fine. Thanks.

I first pulled from docker hub, but still only amd64 platform there. https://hub.docker.com/layers/laromicas/romvault/latest/images/sha256-ed470d59dfd52efe0ec23f7e7293fecb9b9959c24d3752740979c3bc42a7b673?context=explore

**Comment by laromicas** [comment]
Great!
